### ISSUE TITLE
fjs.diff (or maybe .filter)

### ISSUE THREAD

**Issue by rhmg** [leecrossley/functional-js#12]
More a feature request than an issue but still...

standard js comes with .filter which is great but doesn't allow much flexibility when dealing with collections of objects.

would be nice to be able to do the following:

```javascript
var partyGuests = [
   {
      "value1" : "tall",
      "value2" : "bob"
   },
   {
      "value1" : "dark",
      "value2" : "bruce"
   },
   {
      "value1" : "handsome",
      "value2" : "sarah"
   },
   {
      "value1" : "blonde",
      "value2" : "phil"
   }
];
var arrived = [
      "bob", "phil"
];
```

and get a list of "noShows".

**Comment by leecrossley** [comment]
I think I'd use existing fjs functions for this, something like:

    var hasArrived = fjs.select(function (guest) {
        return ~arrived.indexOf(guest.value2);
    }, partyGuests);

**Comment by leecrossley** [comment]
... and if you want noShows (which is what you asked) also using currying:

    var guestsNotArrived = fjs.select(function (guest) {
        return !~arrived.indexOf(guest.value2);
    });

    var noShows = guestsNotArrived(partyGuests);

**Comment by rhmg** [comment]
how about if the arrived was a collection of objects?

so each object has the name and the dish they brought to the party, for example?

**Comment by leecrossley** [comment]
Assume same `partyGuests` and

    var arrived = [
        {
            "value1" : "bob",
            "value2" : "potato salad"
        },
        {
            "value1" : "phil",
            "value2" : "whisky"
        }
    ];

You can just [fjs.pluck](http://functionaljs.com/collections/pluck/) from arrived first:

    var arrivedNames = fjs.pluck("value1", arrived);
    
    var noShows = fjs.select(function (guest) {
        return !~arrivedNames.indexOf(guest.value2);
    }, partyGuests);
