### ISSUE TITLE
Question about Lambda.

### ISSUE THREAD

**Issue by silentrob** [leecrossley/functional-js#13]
How would you represent `λf.λx.f(x)` with functional js? 
It would be nice to be able to just parse it directly, but I suspect I need multiple compose calls?

**Comment by ryansroberts** [comment]
The expression parser is pretty limited and it would probably be unwise to expand it much further.

https://github.com/leecrossley/functional-js/blob/master/functional.js#L11

**Comment by leecrossley** [comment]
The premise is that the library should still feel like Javascript when you use it. Admittedly, we have basic lambda expressions but as Ryan says, we don't plan to expand on this.

There are [projects](https://github.com/search?l=JavaScript&o=desc&q=lambda+calculus&s=stars&type=Repositories&utf8=%E2%9C%93) that do evaluate lambda calculus expressions.

**Comment by silentrob** [comment]
No problem. Thanks for the feedback and rational.
