### ISSUE TITLE
Add the script on home page

### ISSUE THREAD

**Issue by markogresak** [leecrossley/functional-js#14]
It would be great to have the script included on home/docs page so it can be used directly from the console to test some quick code.
If you check out other popular libraries (e.g. underscore, lodash etc.) they have it included too.

**Comment by leecrossley** [comment]
I agree. I did it for [mancjs.functionaljs.com](http://mancjs.functionaljs.com/), should probably find a nice way to include the latest version. Leave it with me :)

**Comment by leecrossley** [comment]
The latest version is now served via [rawgit](https://rawgit.com/).
