### ISSUE TITLE
Seriously???

### ISSUE THREAD

**Issue by sindresorhus** [leecrossley/functional-js#15]
<img width="473" alt="screen shot 2016-03-30 at 00 18 58" src="https://cloud.githubusercontent.com/assets/170270/14117038/fdd1c224-f60c-11e5-8cf7-a5794a9f3ce4.png">

You do realize you're wasting everyone's time with this spammy behavior?

See: https://twitter.com/sindresorhus/status/694999624852045824

**Comment by lukeed** [comment]
![52230353](https://cloud.githubusercontent.com/assets/5855893/14117177/51dd6cbc-f598-11e5-9dae-f204e80c82c2.jpg)

**Comment by leecrossley** [comment]
yeah, sorry dude - didn't expect it to quite be that bad, only let it run for 10 seconds :( I'm ashamed, but, if you want to be a contributor for real, I'm happy to make that happen.
